piotr-grosicki/project-jdp-2405-01

build.gradle
src/main/java/com/kodilla/ecommercee/controller/ProductController.java
src/main/java/com/kodilla/ecommercee/dto/request/CreateProductRequest.java
src/main/java/com/kodilla/ecommercee/dto/request/DeleteProductRequest.java
src/main/java/com/kodilla/ecommercee/dto/request/UpdateProductRequest.java
src/main/java/com/kodilla/ecommercee/dto/response/ProductResponse.java

Dodalem Lombok dependency w build.gradle
Stworzylem ProductController w pakiecie controller ProductController posiada 5 requestow:
getAllProducts - obecnie zwraca pusta liste
getProduct - obecnie pobiera w linku id i zwraca przykladowy ProductResponse z podanym id createProduct - przyjmuje jako argument CreateProductRequest i zwraca przykladowy ProductResponse updateProduct - przymuje jako argument UpdateProductRequest i zwraca przykladowy ProductResponse deleteProduct - przyjmuje jako argument DeleteProductRequest i zwraca przykladowy ProductResponse
Stworzylem rowniez dto request i response gdzie beda przechowywane dto

JDP240501-01-ProductController wstepna implementacja

---

src/main/java/com/kodilla/ecommercee/controller/UserController.java
src/main/java/com/kodilla/ecommercee/dto/request/CreateUserRequest.java
src/main/java/com/kodilla/ecommercee/dto/request/UpdateUserRequest.java
src/main/java/com/kodilla/ecommercee/dto/response/UserResponse.java

Requesty zwracają przykładowe dane.

JDP-2405-05-UserController-wstepna-implementacja 

---

src/main/java/com/kodilla/ecommercee/controller/CartController.java
src/main/java/com/kodilla/ecommercee/controller/OrderController.java
src/main/java/com/kodilla/ecommercee/dto/request/AddProductToCartRequest.java
src/main/java/com/kodilla/ecommercee/dto/request/CreateCartRequest.java
src/main/java/com/kodilla/ecommercee/dto/request/GetCartRequest.java
src/main/java/com/kodilla/ecommercee/dto/request/GetProductFromCartRequest.java
src/main/java/com/kodilla/ecommercee/dto/request/RemoveProductFromCartRequest.java
src/main/java/com/kodilla/ecommercee/dto/response/CartResponse.java
src/main/java/com/kodilla/ecommercee/dto/response/OrderResponse.java

Swtorzylem CartController:
getAllProductsFromCart - zwraca liste produktow z danego koszyka 
createCart - tworzy pusty koszyk
addProductToCart - dodaje produkt do koszyka
createOrderFromCart - tworzy order z danego koszyka 
deleteProductFromCart - usuwa produkt z koszyka
W OrderResponse zmienilem typ totalPrice z Double na BigDecimal

JDP240501-03-CartController-wstepna-implementacja

---

.gitignore
src/main/java/com/kodilla/ecommercee/controller/GroupController.java
src/main/java/com/kodilla/ecommercee/dto/request/CreateGroupRequest.java
src/main/java/com/kodilla/ecommercee/dto/request/UpdateGroupRequest.java
src/main/java/com/kodilla/ecommercee/dto/response/GroupResponse.java
src/main/resources/application.yaml

Wstępna implementacja GroupController

Jdp 2405 02 group controller wstepna implementacja

---

src/main/java/com/kodilla/ecommercee/entity/Cart.java
src/main/java/com/kodilla/ecommercee/entity/Order.java
src/main/java/com/kodilla/ecommercee/entity/User.java
src/main/java/com/kodilla/ecommercee/repository/OrderRepository.java

Stworzylem encje Order narazie bez polaczen; czekam az encja user oraz cart zostana dodane, wtedy dodam polaczenia z orderem. Narazie pola dot. polaczen ustawilem Long pole w momencie utworzenia encji zmienie te typy na User user oraz Cart cart;

JDP-2405-01-11 encja order - implementacja

---

src/main/java/com/kodilla/ecommercee/entity/Cart.java
src/main/java/com/kodilla/ecommercee/entity/Order.java
src/main/java/com/kodilla/ecommercee/entity/User.java
src/main/java/com/kodilla/ecommercee/repository/UserRepository.java

Utworzylem encje User wraz z repozytorium oraz wydmuszki dla cart i order.

JDP240501-15-encja-user-implementacja

---

build.gradle
src/main/java/com/kodilla/ecommercee/entities/Cart.java
src/main/java/com/kodilla/ecommercee/entities/Group.java
src/main/java/com/kodilla/ecommercee/entities/Product.java
src/main/java/com/kodilla/ecommercee/repositories/ProductRepository.java

- Dodałem encję Product i repozytorium ProductRepository
- Czekam z wprowadzeniem relacji na implementację encji group i cart
- Dodałem import w gradle.build dla adnotacji @NotNull

JDP240501-12-Product-implementacja-encji

---

src/main/java/com/kodilla/ecommercee/entity/Product.java
src/main/java/com/kodilla/ecommercee/repository/ProductRepository.java

Dodano pola price i quantity w product, scalono repository i repositories

JDP240501-26-scalenie-repository-i-repositories 

---

src/main/java/com/kodilla/ecommercee/entity/Group.java
src/main/java/com/kodilla/ecommercee/repository/GroupRepository.java

Encja Group zbudowana na Group z aktualnego main.

JDP-240501-13 - Encja Group utworzona po fixie Sebczaka

---

build.gradle
src/main/java/com/kodilla/ecommercee/entity/Product.java
src/test/java/com/kodilla/ecommercee/entity/GroupTestSuite.java

Oprócz testów odałem annotationProcessor, bez którego nie działały adnotacje lomboka

JDP240501-18-encja-group-testy

---

build.gradle
src/main/java/com/kodilla/ecommercee/entity/Product.java
src/test/java/com/kodilla/ecommercee/entity/ProductTestSuite.java

Napisalem testy jednostkowe product: GetAll, GetOne, Create, Update, Delete. Oprocz tego usunalem @NotNull z id w encji Product. Dodałem też annotationProcessor 'org.projectlombok:lombok' do build.gradle - bez tego nie działały mi adnotacje z Lomboka. Pytanie czy chcemy dodać tą linijkę do main

Testy jednostkowe encji product

---

src/main/java/com/kodilla/ecommercee/entity/Cart.java
src/main/java/com/kodilla/ecommercee/entity/Order.java
src/main/java/com/kodilla/ecommercee/entity/User.java
src/test/java/com/kodilla/ecommercee/entity/OrderTestSuite.java

Dodalem annotacje Builder dla encji Cart, Order i User. Lekko zmodyfikowalem tworzenie obiektow encji w testach.

JDP-2405-01-28 poprawienie testow Order

---

build.gradle
src/main/java/com/kodilla/ecommercee/entity/Cart.java
src/main/java/com/kodilla/ecommercee/entity/Group.java
src/main/java/com/kodilla/ecommercee/entity/Order.java
src/main/java/com/kodilla/ecommercee/entity/Product.java
src/main/java/com/kodilla/ecommercee/entity/User.java
src/test/java/com/kodilla/ecommercee/entity/CartTestSuite.java
src/test/java/com/kodilla/ecommercee/entity/UserTestSuite.java

Poprawilem testy do Cart i User
Pousuwalem Buildera z encji w ktorych byl dodany
Dodalem odstepy miedzy polami tak zeby encje wygladaly jednolicie
Usunalem zduplikowane dependency Lomboka

JDP-2405-01-19-Cart-encja-testy

---

src/main/java/com/kodilla/ecommercee/controller/OrderController.java
src/main/java/com/kodilla/ecommercee/dto/request/CreateOrderRequest.java
src/main/java/com/kodilla/ecommercee/dto/request/UpdateOrderRequest.java

- Z OrderControllera wyrzuciłem metodę oznaczoną @PostMapping
- Zmieniłem parametry rekordu UpdateOrderRequest (wyrzuciłem cartId i userId)
- zmieniłem ścieżkę @RequestMapping na końcówkę "order" bo zauważyłem, że taka jest konwencja w pozostałych controllerach

JDP-240501-30 - OrderController - poprawki po opinii PM

---

src/main/java/com/kodilla/ecommercee/entity/User.java

Dodanie pola token do encji User.

JDP-2405-01-33 encja User dodanie pola token

---

src/main/java/com/kodilla/ecommercee/controller/CartController.java
src/main/java/com/kodilla/ecommercee/dto/request/GetCartRequest.java

Poprawienie metody w CartController. Teraz getAllProductsFromCart przyjmuje PathVariable cartId zamiast Requestu. Dodatkowo usunalem zbedny request z dto.

JDP-2405-01-32 CartController poprawienie metody

---

src/main/java/com/kodilla/ecommercee/controller/CartController.java
src/main/java/com/kodilla/ecommercee/controller/GroupController.java
src/main/java/com/kodilla/ecommercee/controller/ProductController.java
src/main/java/com/kodilla/ecommercee/dto/response/GroupResponse.java
src/main/java/com/kodilla/ecommercee/dto/response/ProductResponse.java
src/main/java/com/kodilla/ecommercee/entity/Group.java
src/main/java/com/kodilla/ecommercee/exception/GroupHasProductsException.java
src/main/java/com/kodilla/ecommercee/exception/GroupNotFoundException.java
src/main/java/com/kodilla/ecommercee/mapper/GroupMapper.java
src/main/java/com/kodilla/ecommercee/service/GroupService.java

dodalem serwis z metodami do wszystkich metod dla GroupController
poprawilem ProductResponse rekord (przez to musialem fixnac CartController i ProductController)
Stworzylem GroupService
Stworzylem mapping do Grupy
Stworzylem customowe wyjatki dla grupy

JDP-2405-01-22 GroupController implementacja metod

---

src/main/java/com/kodilla/ecommercee/exception/GlobalHttpErrorHandler.java
src/main/java/com/kodilla/ecommercee/exception/GroupHasProductsException.java
src/main/java/com/kodilla/ecommercee/exception/GroupNotFoundException.java
src/main/java/com/kodilla/ecommercee/service/GroupService.java

Poprawilem wyjatki dla GroupService oraz stworzylem GlobalHttpErrorHandler ktora zwraca do frontendu co poszlo nie tak. Zmienilem tez atrybuty dla metod GroupService z id na groupId dla lepszej czytelnosci.

JDP-2405-01-34 Poprawienie wyjatkow OrderService

---

src/main/java/com/kodilla/ecommercee/controller/CartController.java
src/main/java/com/kodilla/ecommercee/controller/ProductController.java
src/main/java/com/kodilla/ecommercee/dto/request/CreateProductRequest.java
src/main/java/com/kodilla/ecommercee/dto/request/DeleteProductRequest.java
src/main/java/com/kodilla/ecommercee/dto/request/UpdateProductRequest.java
src/main/java/com/kodilla/ecommercee/dto/response/GroupResponse.java
src/main/java/com/kodilla/ecommercee/dto/response/ProductResponse.java
src/main/java/com/kodilla/ecommercee/exception/GlobalHttpErrorHandler.java
src/main/java/com/kodilla/ecommercee/exception/NegativeValuesException.java
src/main/java/com/kodilla/ecommercee/exception/NullValueException.java
src/main/java/com/kodilla/ecommercee/exception/ProductNotFoundException.java
src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
src/main/java/com/kodilla/ecommercee/service/ProductService.java

- W rekordach CreateProductRequest i UpdateProductRequest dodałem pola: price, quantity i group.
- Usunąłem DeleteProductRequest
- W ProductResponse zrobiłem @JsonIgnoreProperties dla pola productList z Group group
W GroupResponse zrobiłem @JsonIgnoreProperties dla pola group z List<Product> products. Bez tego zapisu Product i Group wzajemnie się zapętlały i przy żądaniu GET odpowiedź w Postmanie miała ponad 5000 linijek :).
- Utworzyłem 2 typy wyjątków (ogólny by w niektórych przypadkach nie przyjmowało null i błędny id produktu)
- Utworzyłem GlobalHandlingException by dawało jakąś odpowiedź w JSON.
- CartController (wstępna implementacja) uzupełniłem o przykładową wartość dla pola typu Group. 
- Zrobiłem rzeczywistą implementację ProductController
- Utworzyłem ProductMapper
- Utworzyłem …

JDP-240501-21 - ProductController - rzeczywista implementacja

---

src/main/java/com/kodilla/ecommercee/controller/CartController.java
src/main/java/com/kodilla/ecommercee/controller/OrderController.java
src/main/java/com/kodilla/ecommercee/dto/request/AddProductToCartRequest.java
src/main/java/com/kodilla/ecommercee/dto/request/CreateOrderRequest.java
src/main/java/com/kodilla/ecommercee/dto/response/CartItemResponse.java
src/main/java/com/kodilla/ecommercee/dto/response/CartResponse.java
src/main/java/com/kodilla/ecommercee/dto/response/OrderResponse.java
src/main/java/com/kodilla/ecommercee/entity/Cart.java
src/main/java/com/kodilla/ecommercee/entity/CartItem.java
src/main/java/com/kodilla/ecommercee/entity/Product.java
src/main/java/com/kodilla/ecommercee/exception/CartNotFoundException.java
src/main/java/com/kodilla/ecommercee/exception/GlobalHttpErrorHandler.java
src/main/java/com/kodilla/ecommercee/exception/ProductNotFoundException.java
src/main/java/com/kodilla/ecommercee/exception/UserNotFoundException.java
src/main/java/com/kodilla/ecommercee/mapper/CartItemMapper.java
src/main/java/com/kodilla/ecommercee/mapper/CartMapper.java
src/main/java/com/kodilla/ecommercee/mapper/OrderMapper.java
src/main/java/com/kodilla/ecommercee/mapper/ProductMapper.java
src/main/java/com/kodilla/ecommercee/repository/CartItemRepository.java
src/main/java/com/kodilla/ecommercee/service/CartService.java
src/test/java/com/kodilla/ecommercee/entity/CartItemTestSuite.java
src/test/java/com/kodilla/ecommercee/entity/CartTestSuite.java

- Dodałem CartService
- Dodałem wyjątki potrzebne do obsługi CartService
- Dodałem Mapper dla Carta
- Z recordu CartResponse usunąłem pole Quantity - jest niepotrzebne w tym miejscu
- Do recordu AddProductToCartRequest dodałem pole, cartId
----
- dodałem metody deleteProductFromCart i createOrderFromCart w CartService
- dodałem rzeczywistą implementację metod w CartController
- w CartController zmieniłem adres endpointu createOrderFromCart przyjmujący zmienną na /order i wymagający podania request body, zamiast zmiennej w adresie
- dodałem pole shippingAddress w CreateOrderRequest
- usunąłem pole price z AddProductToCartRequest
- w OrderResponse zmieniłem status na boolean
- dodałem OrderMapper skopiowany z brancha implementującego order na potrzeby CartService

JDP240501-23-CartController-implementacja

---

src/main/java/com/kodilla/ecommercee/entity/Cart.java

Poprawilem konstruktor Cart i teraz tworzenie pustego koszyka dziala

JDP-2405-01 37 fix tworzenie pustego carta

---

build.gradle
src/main/java/com/kodilla/ecommercee/controller/CartController.java
src/main/java/com/kodilla/ecommercee/controller/GroupController.java
src/main/java/com/kodilla/ecommercee/controller/OrderController.java
src/main/java/com/kodilla/ecommercee/controller/ProductController.java
src/main/java/com/kodilla/ecommercee/controller/UserController.java
src/main/java/com/kodilla/ecommercee/dto/request/CreateProductRequest.java
src/main/java/com/kodilla/ecommercee/dto/request/UpdateProductRequest.java
src/main/java/com/kodilla/ecommercee/exception/GlobalHttpErrorHandler.java
src/main/java/com/kodilla/ecommercee/exception/InvalidTokenException.java
src/main/java/com/kodilla/ecommercee/exception/NegativeValuesException.java
src/main/java/com/kodilla/ecommercee/processor/TokenValidationProcessor.java
src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
src/main/java/com/kodilla/ecommercee/service/ProductService.java

Dodalem spring aop dependency
Dodalem atrybut token we wszystkich requestach oprocz tworzenia usera i logowania
Dodalem custom wyjatek InvalidTokenException, ktory zwraca czy token jest poprawny czy nie
Dodalem klase TokenValidationProcessor, ktora uzywa AOP do sprawdzenia czy token jest poprawny
Poprawilem w CreateProductRequest grupe tak aby pobieralo tylko id grupy nie cala grupe i tak samo w UpdateProductRequest
I usunalem EnableAspectJAutoProxy oraz zbedne importy

JDP-2405-01 36 walidacja user tokena
